/*
 * pogls_graph_topology.h — POGLS V3.5 Graph Topology
 *
 * 162-node icosphere L2 (TOPO_STANDARD) adjacency table
 * Layout: CSR (Compressed Sparse Row) — offset + count + flat edge list
 *
 * Ring-diffusion pattern: n → n±1, n±9, n±27  (mod 162)
 *   - degree = 6 (uniform)
 *   - diffusion radius 1: covers ~37 nodes
 *   - diffusion radius 2: covers ~127 nodes
 *   - branchless, SIMD-friendly, cache-local
 *
 * ห้าม include pogls_hydra.h / pogls_snapshot.h ใน header นี้
 */

#ifndef POGLS_GRAPH_TOPOLOGY_H
#define POGLS_GRAPH_TOPOLOGY_H

#include <stdint.h>
#include "pogls_node_soa.h"   /* NODE_MAX, NodeMask, nodemask_set */

/* ═══════════════════════════════════════════════════════════════════════
   TOPOLOGY CONSTANTS
   ═══════════════════════════════════════════════════════════════════════ */

#define TOPO_NODE_MAX     162
#define TOPO_DEGREE       6
#define TOPO_EDGE_COUNT   972   /* NODE_MAX × DEGREE */
#define TOPO_MIN_DEGREE   6
#define TOPO_MAX_DEGREE   6

/* ═══════════════════════════════════════════════════════════════════════
   CSR ADJACENCY TABLE
   adjacency_offset[n] → start index ใน adjacency_table[]
   adjacency_count[n]  → จำนวน neighbors ของ node n
   adjacency_table[]   → flat list of neighbor node ids
   ═══════════════════════════════════════════════════════════════════════ */

/* stride = 6 (uniform degree) — offset[n] = n*6 */
static const uint16_t adjacency_offset[TOPO_NODE_MAX] = {
      0,  6, 12, 18, 24, 30, 36, 42, 48, 54,
     60, 66, 72, 78, 84, 90, 96,102,108,114,
    120,126,132,138,144,150,156,162,168,174,
    180,186,192,198,204,210,216,222,228,234,
    240,246,252,258,264,270,276,282,288,294,
    300,306,312,318,324,330,336,342,348,354,
    360,366,372,378,384,390,396,402,408,414,
    420,426,432,438,444,450,456,462,468,474,
    480,486,492,498,504,510,516,522,528,534,
    540,546,552,558,564,570,576,582,588,594,
    600,606,612,618,624,630,636,642,648,654,
    660,666,672,678,684,690,696,702,708,714,
    720,726,732,738,744,750,756,762,768,774,
    780,786,792,798,804,810,816,822,828,834,
    840,846,852,858,864,870,876,882,888,894,
    900,906,912,918,924,930,936,942,948,954,
    960,966
};

/* uniform degree 6 for all nodes */
static const uint8_t adjacency_count[TOPO_NODE_MAX] = {
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6,6,6,6,6,6,6,6,6, 6,6,6,6,6,6,6,6,6,6,
    6,6
};

/*
 * adjacency_table[972] — flat neighbor list (ring-diffusion, mod 162)
 *   per node n: {n+1, n-1, n+9, n-9, n+27, n-27} mod 162
 *
 * generated by topo_build_adjacency() at init — ไม่ฝัง static เพราะ
 * ขนาด 972×2B = 1944B ยัง fit L2 และ build cost < 1µs
 *
 * ถ้าต้องการ ROM table: run topo_dump_c() แล้ว paste ที่นี่
 */
extern uint16_t topo_adjacency_table[TOPO_EDGE_COUNT];

/* ═══════════════════════════════════════════════════════════════════════
   BUILD & QUERY API
   ═══════════════════════════════════════════════════════════════════════ */

/*
 * topo_build_adjacency — สร้าง adjacency_table ตอน startup
 * เรียกครั้งเดียวก่อน engine เริ่ม
 */
void topo_build_adjacency(uint16_t *table);

/*
 * topo_build_edge_masks — สร้าง NodeMask ของ neighbors ต่อ node
 * เขียนลง edge_masks[NODE_MAX]
 * เรียกหลัง topo_build_adjacency()
 */
void topo_build_edge_masks(const uint16_t *table, NodeMask *edge_masks);

/* traversal helper */
static inline void topo_for_each_neighbor(
        const uint16_t *table,
        uint32_t node,
        void (*cb)(uint32_t neighbor, void *ud),
        void *ud)
{
    uint16_t off = adjacency_offset[node];
    uint8_t  cnt = adjacency_count[node];
    for (uint8_t i = 0; i < cnt; i++)
        cb(table[off + i], ud);
}

/* ═══════════════════════════════════════════════════════════════════════
   NTACLE DIFFUSION (graph propagation)
   ═══════════════════════════════════════════════════════════════════════ */

/*
 * topo_diffuse_fast — one diffusion pass, bit-scan loop
 *
 * input:  active  (nodes that fired this tick)
 * output: out     (nodes to activate next tick, union of neighbors)
 *
 * latency: ~40-70ns for typical active set
 */
static inline NodeMask topo_diffuse_fast(
        const NodeMask  *active,
        const NodeMask  *edge_masks)
{
    NodeMask out = *active;

    for (int w = 0; w < 3; w++) {        /* word 3 = padding, skip */
        uint64_t bits = active->w[w];
        while (bits) {
            int      b    = __builtin_ctzll(bits);
            bits         &= bits - 1;
            int      node = (w << 6) | b;
            if (node >= TOPO_NODE_MAX) break;
            const NodeMask *e = &edge_masks[node];
            out.w[0] |= e->w[0];
            out.w[1] |= e->w[1];
            out.w[2] |= e->w[2];
            out.w[3] |= e->w[3];
        }
    }
    return out;
}

/*
 * topo_spread — multi-step diffusion
 * steps=1: neighbors only
 * steps=2: neighbors + neighbors-of-neighbors
 */
static inline NodeMask topo_spread(
        NodeMask        m,
        const NodeMask *edge_masks,
        int             steps)
{
    for (int i = 0; i < steps; i++)
        m = topo_diffuse_fast(&m, edge_masks);
    return m;
}

/* ═══════════════════════════════════════════════════════════════════════
   DETACH INTEGRATION
   ═══════════════════════════════════════════════════════════════════════ */

/*
 * topo_detach_spread — diffuse ใน scope ของ DetachFrame.ntacle_mask
 * ไม่ scan graph ทั้งหมด — เฉพาะ nodes ที่เกี่ยวข้อง
 *
 * ntacle_mask : bitmask ของ nodes ใน detached zone
 * edge_masks  : precomputed ของ full graph
 */
static inline NodeMask topo_detach_spread(
        uint64_t        ntacle_mask,
        const NodeMask *edge_masks,
        int             steps)
{
    NodeMask m;
    m.w[0] = ntacle_mask;   /* node 0-63  */
    m.w[1] = 0;
    m.w[2] = 0;
    m.w[3] = 0;
    return topo_spread(m, edge_masks, steps);
}

/* ═══════════════════════════════════════════════════════════════════════
   DEBUG UTIL
   ═══════════════════════════════════════════════════════════════════════ */

/* dump adjacency_table เป็น C source — ใช้ generate static table */
void topo_dump_c(const uint16_t *table);

#endif /* POGLS_GRAPH_TOPOLOGY_H */
